tasks:
  - name: Frontend Dev Server
    init: npm install && npm run build
    command: npm run dev
  - name: Amplify Sandbox
    init: npm install -g @aws-amplify/cli@latest  # Ensure latest CLI globally
    command: npx ampx sandbox --profile admin